"""Backend tasks package"""
from .core import predict_crop_task, process_loan_task, synthesize_loan_pdf_task, finalize_pool_cycle_task, simulate_batch_payouts_task, check_pool_target_reached_task
from .report_tasks import generate_and_send_report, generate_pdf_report, send_email_report, batch_generate_reports
from .traceability_tasks import generate_batch_certificate_task
from .knowledge_tasks import calculate_trending_questions_task, expert_verification_audit_task
from .weather_tasks import fetch_weather_updates_task, generate_bulk_advisories_task
from .rental_tasks import check_overdue_rentals_task, cleanup_expired_pending_bookings_task
from .farm_tasks import monthly_farm_valuation_task, generate_farm_report_task
from .sustainability_tasks import recalculate_all_offsets_task, stale_audit_check_task, annual_credit_revaluation_task
from .procurement_tasks import procurement_payment_reminders_task, vendor_payout_settlement_task
from .irrigation_tasks import poll_sensor_telemetry_task, irrigation_health_audit_task
from .processing_tasks import monitor_stale_batches_task, daily_production_report_task
from .insurance_tasks import insurance_policy_expiry_check_task, weather_risk_monitor_task
from .machinery_tasks import check_maintenance_intervals_task, machinery_valuation_update_task
from .soil_tasks import generate_seasonal_soil_reports_task, fertilizer_application_reminder_task
from .loan_tasks import daily_payment_reminders_task, overdue_escalation_task, monthly_risk_recalculation_task
from .warehouse_tasks import daily_expiry_alerts_task, automated_reorder_notifications_task, monthly_reconciliation_reminder_task
from .climate_tasks import check_sensor_health_task, generate_env_report_task, purge_old_telemetry_task
from .pathogen_tasks import pathogen_propagation_run, analyze_new_incident
from .transparency_tasks import hourly_freshness_pricing_update, sync_reputation_feedback
from .soil_sync import precision_fertigation_sync, update_nutrient_maps
from .logistics_tasks import global_tracking_sync, run_compliance_audit
from .maintenance_tasks import fleet_reliability_audit, check_maintenance_cycles
from .fx_tasks import (
    sync_fx_rates_task, trigger_ledger_revaluation_task,
    revalue_vault_task, detect_significant_rate_shifts_task,
    backfill_historical_rates_task, cleanup_old_rates_task,
    compute_fx_exposure_alerts_task, daily_fx_rate_sync_task
) 
