"""Add full_name to users

Revision ID: 8be05540cfac
Revises: 
Create Date: 2026-01-30 23:45:47.158504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be05540cfac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.drop_column('email_enabled')
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('sms_enabled')
        batch_op.drop_column('language_preference')
        batch_op.drop_column('is_email_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_email_verified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('language_preference', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('sms_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('email_verified_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('email_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.drop_column('role')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
